<Project>
  <PropertyGroup>
    <Version>1.2.2</Version>
    <VersionPrefix>1.2.2</VersionPrefix>
    <VersionSuffix></VersionSuffix>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <InformationalVersion>1.2.2</InformationalVersion>
    <Product>VRS Race Control 1.2.2</Product>
  </PropertyGroup>
</Project>
