[build]
builder = "nixpacks"
buildCommand = "dotnet publish src/VRS.RaceControl.Relay/VRS.RaceControl.Relay.csproj -c Release -o publish"

[deploy]
startCommand = "dotnet publish/VRS.RaceControl.Relay.dll"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
