<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Version>1.2.2</Version>
    <VersionPrefix>1.2.2</VersionPrefix>
    <InformationalVersion>1.2.2</InformationalVersion>
    <AssemblyVersion>1.2.2.0</AssemblyVersion>
    <FileVersion>1.2.2.0</FileVersion>
    <Product>VRS Race Control Relay 1.2.2</Product>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <!-- Allow deploying as single Linux binary on Railway/Render -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRS.RaceControl.Shared\VRS.RaceControl.Shared.csproj" />
  </ItemGroup>

</Project>
